general_train_mode: true
general_task: instance_segmentation
general_seed: null
general_checkpoint: null
general_backbone_checkpoint: null
general_freeze_backbone: false
general_linear_probing_backbone: false
general_train_on_segments: false
general_eval_on_segments: false
general_filter_out_instances: false
general_save_visualizations: false
general_visualization_point_size: 20
general_decoder_id: -1
general_export: false
general_use_dbscan: false
general_ignore_class_threshold: 100
general_project_name: fallentree
general_experiment_name: fallentree_mask3d
general_num_targets: 2
general_add_instance: true
general_dbscan_eps: 0.95
general_dbscan_min_points: 1
general_export_threshold: 0.0001
general_reps_per_epoch: 1
general_on_crops: false
general_scores_threshold: 0.0
general_iou_threshold: 1.0
general_object_score_threshold: 0.5
general_object_iou_threshold: 0.5
general_save_las: true
general_las_output_dir: saved/fallentree_mask3d/las_predictions
general_area: 5
general_eval_inner_core: -1
general_topk_per_image: 100
general_ignore_mask_idx: []
general_max_batch_size: 99999999
general_save_dir: saved/fallentree_mask3d
general_gpus: 1
data_train_mode: train
data_validation_mode: validation
data_test_mode: test
data_ignore_label: 255
data_add_raw_coordinates: true
data_add_colors: true
data_add_normals: true
data_in_channels: 6
data_num_labels: 2
data_add_instance: true
data_task: instance_segmentation
data_pin_memory: true
data_num_workers: 8
data_batch_size: 5
data_test_batch_size: 1
data_cache_data: false
data_voxel_size: 0.15
data_reps_per_epoch: 1
data_cropping: false
data_cropping_args_min_points: 30
data_cropping_args_aspect: 0.8
data_cropping_args_min_crop: 0.5
data_cropping_args_max_crop: 1.0
data_crop_min_size: 20
data_crop_length: 2000.0
data_cropping_v1: false
data_train_dataloader__target_: torch.utils.data.DataLoader
data_train_dataloader_shuffle: true
data_train_dataloader_pin_memory: true
data_train_dataloader_num_workers: 8
data_train_dataloader_batch_size: 5
data_validation_dataloader__target_: torch.utils.data.DataLoader
data_validation_dataloader_shuffle: false
data_validation_dataloader_pin_memory: true
data_validation_dataloader_num_workers: 8
data_validation_dataloader_batch_size: 1
data_test_dataloader__target_: torch.utils.data.DataLoader
data_test_dataloader_shuffle: false
data_test_dataloader_pin_memory: true
data_test_dataloader_num_workers: 8
data_test_dataloader_batch_size: 1
data_train_dataset__target_: datasets.semseg.SemanticSegmentationDataset
data_train_dataset_dataset_name: stpls3d_fallentree
data_train_dataset_data_dir: data/processed/stpls3d_fallentree
data_train_dataset_image_augmentations_path: conf/augmentation/albumentations_aug.yaml
data_train_dataset_volume_augmentations_path: conf/augmentation/volumentations_aug.yaml
data_train_dataset_label_db_filepath: data/processed/stpls3d_fallentree/label_database.yaml
data_train_dataset_color_mean_std: data/processed/stpls3d_fallentree/color_mean_std.yaml
data_train_dataset_data_percent: 1.0
data_train_dataset_mode: train
data_train_dataset_ignore_label: 255
data_train_dataset_num_labels: 2
data_train_dataset_add_raw_coordinates: true
data_train_dataset_add_colors: true
data_train_dataset_add_normals: true
data_train_dataset_add_instance: true
data_train_dataset_cache_data: false
data_train_dataset_instance_oversampling: 0.0
data_train_dataset_place_around_existing: false
data_train_dataset_point_per_cut: 0
data_train_dataset_max_cut_region: 0
data_train_dataset_flip_in_center: false
data_train_dataset_noise_rate: 0
data_train_dataset_resample_points: 0
data_train_dataset_cropping: false
data_train_dataset_cropping_args_min_points: 30
data_train_dataset_cropping_args_aspect: 0.8
data_train_dataset_cropping_args_min_crop: 0.5
data_train_dataset_cropping_args_max_crop: 1.0
data_train_dataset_is_tta: false
data_train_dataset_crop_min_size: 20
data_train_dataset_crop_length: 2000.0
data_train_dataset_cropping_v1: false
data_train_dataset_area: 5
data_train_dataset_reps_per_epoch: 1
data_train_dataset_eval_inner_core: -1
data_train_dataset_filter_out_classes:
- 0
data_train_dataset_label_offset: 1
data_train_dataset_is_elastic_distortion: true
data_train_dataset_color_drop: 0.0
data_validation_dataset__target_: datasets.semseg.SemanticSegmentationDataset
data_validation_dataset_dataset_name: stpls3d_fallentree
data_validation_dataset_data_dir: data/processed/stpls3d_fallentree
data_validation_dataset_image_augmentations_path: null
data_validation_dataset_volume_augmentations_path: null
data_validation_dataset_label_db_filepath: data/processed/stpls3d_fallentree/label_database.yaml
data_validation_dataset_color_mean_std: data/processed/stpls3d_fallentree/color_mean_std.yaml
data_validation_dataset_data_percent: 1.0
data_validation_dataset_mode: validation
data_validation_dataset_ignore_label: 255
data_validation_dataset_num_labels: 2
data_validation_dataset_add_raw_coordinates: true
data_validation_dataset_add_colors: true
data_validation_dataset_add_normals: true
data_validation_dataset_add_instance: true
data_validation_dataset_cache_data: false
data_validation_dataset_cropping: false
data_validation_dataset_is_tta: false
data_validation_dataset_crop_min_size: 20
data_validation_dataset_crop_length: 2000.0
data_validation_dataset_cropping_v1: false
data_validation_dataset_area: 5
data_validation_dataset_on_crops: false
data_validation_dataset_eval_inner_core: -1
data_validation_dataset_filter_out_classes:
- 0
data_validation_dataset_label_offset: 1
data_test_dataset__target_: datasets.semseg.SemanticSegmentationDataset
data_test_dataset_dataset_name: stpls3d_fallentree
data_test_dataset_data_dir: data/processed/stpls3d_fallentree
data_test_dataset_image_augmentations_path: null
data_test_dataset_volume_augmentations_path: null
data_test_dataset_label_db_filepath: data/processed/stpls3d_fallentree/label_database.yaml
data_test_dataset_color_mean_std: data/processed/stpls3d_fallentree/color_mean_std.yaml
data_test_dataset_data_percent: 1.0
data_test_dataset_mode: test
data_test_dataset_ignore_label: 255
data_test_dataset_num_labels: 2
data_test_dataset_add_raw_coordinates: true
data_test_dataset_add_colors: true
data_test_dataset_add_normals: true
data_test_dataset_add_instance: true
data_test_dataset_cache_data: false
data_test_dataset_cropping: false
data_test_dataset_is_tta: false
data_test_dataset_crop_min_size: 20
data_test_dataset_crop_length: 2000.0
data_test_dataset_cropping_v1: false
data_test_dataset_area: 5
data_test_dataset_on_crops: false
data_test_dataset_eval_inner_core: -1
data_test_dataset_filter_out_classes:
- 0
data_test_dataset_label_offset: 1
data_train_collation__target_: datasets.utils.VoxelizeCollate
data_train_collation_ignore_label: 255
data_train_collation_voxel_size: 0.15
data_train_collation_mode: train
data_train_collation_small_crops: false
data_train_collation_very_small_crops: false
data_train_collation_batch_instance: false
data_train_collation_probing: false
data_train_collation_task: instance_segmentation
data_train_collation_ignore_class_threshold: 100
data_train_collation_filter_out_classes:
- 0
data_train_collation_label_offset: 1
data_train_collation_num_queries: 100
data_validation_collation__target_: datasets.utils.VoxelizeCollate
data_validation_collation_ignore_label: 255
data_validation_collation_voxel_size: 0.15
data_validation_collation_mode: validation
data_validation_collation_batch_instance: false
data_validation_collation_probing: false
data_validation_collation_task: instance_segmentation
data_validation_collation_ignore_class_threshold: 100
data_validation_collation_filter_out_classes:
- 0
data_validation_collation_label_offset: 1
data_validation_collation_num_queries: 100
data_test_collation__target_: datasets.utils.VoxelizeCollate
data_test_collation_ignore_label: 255
data_test_collation_voxel_size: 0.15
data_test_collation_mode: test
data_test_collation_batch_instance: false
data_test_collation_probing: false
data_test_collation_task: instance_segmentation
data_test_collation_ignore_class_threshold: 100
data_test_collation_filter_out_classes:
- 0
data_test_collation_label_offset: 1
data_test_collation_num_queries: 100
logging:
- _target_: pytorch_lightning.loggers.CSVLogger
  save_dir: saved/fallentree_mask3d
  name: lightning_logs
model__target_: models.Mask3D
model_hidden_dim: 128
model_dim_feedforward: 1024
model_num_queries: 100
model_num_heads: 8
model_num_decoders: 3
model_dropout: 0.0
model_pre_norm: false
model_use_level_embed: false
model_normalize_pos_enc: true
model_positional_encoding_type: fourier
model_gauss_scale: 1.0
model_hlevels:
- 0
- 1
- 2
- 3
model_non_parametric_queries: true
model_random_query_both: false
model_random_normal: false
model_random_queries: false
model_use_np_features: false
model_sample_sizes:
- 200
- 800
- 3200
- 12800
- 51200
model_max_sample_size: false
model_shared_decoder: true
model_num_classes: 2
model_train_on_segments: false
model_scatter_type: mean
model_voxel_size: 0.15
model_config_backbone__target_: models.Res16UNet34C
model_config_backbone_config_dialations:
- 1
- 1
- 1
- 1
model_config_backbone_config_conv1_kernel_size: 5
model_config_backbone_config_bn_momentum: 0.02
model_config_backbone_in_channels: 6
model_config_backbone_out_channels: 2
model_config_backbone_out_fpn: true
metrics__target_: models.metrics.ConfusionMatrix
metrics_num_classes: 2
metrics_ignore_label: 255
optimizer__target_: torch.optim.AdamW
optimizer_lr: 0.0001
scheduler_scheduler__target_: torch.optim.lr_scheduler.OneCycleLR
scheduler_scheduler_max_lr: 0.0001
scheduler_scheduler_epochs: 1000
scheduler_scheduler_steps_per_epoch: -1
scheduler_pytorch_lightning_params_interval: step
trainer_deterministic: false
trainer_max_epochs: 1000
trainer_min_epochs: 1
trainer_resume_from_checkpoint: null
trainer_check_val_every_n_epoch: 1
trainer_num_sanity_val_steps: 0
callbacks:
- _target_: pytorch_lightning.callbacks.LearningRateMonitor
matcher__target_: models.matcher.HungarianMatcher
matcher_cost_class: 2.0
matcher_cost_mask: 5.0
matcher_cost_dice: 2.0
matcher_num_points: -1
loss__target_: models.criterion.SetCriterion
loss_num_classes: 2
loss_eos_coef: 0.1
loss_losses:
- labels
- masks
loss_num_points: -1
loss_oversample_ratio: 3.0
loss_importance_sample_ratio: 0.75
loss_class_weights: -1
config:
  general:
    train_mode: true
    task: instance_segmentation
    seed: null
    checkpoint: null
    backbone_checkpoint: null
    freeze_backbone: false
    linear_probing_backbone: false
    train_on_segments: false
    eval_on_segments: false
    filter_out_instances: false
    save_visualizations: false
    visualization_point_size: 20
    decoder_id: -1
    export: false
    use_dbscan: false
    ignore_class_threshold: 100
    project_name: fallentree
    experiment_name: fallentree_mask3d
    num_targets: 2
    add_instance: true
    dbscan_eps: 0.95
    dbscan_min_points: 1
    export_threshold: 0.0001
    reps_per_epoch: 1
    on_crops: false
    scores_threshold: 0.0
    iou_threshold: 1.0
    object_score_threshold: 0.5
    object_iou_threshold: 0.5
    save_las: true
    las_output_dir: saved/fallentree_mask3d/las_predictions
    area: 5
    eval_inner_core: -1
    topk_per_image: 100
    ignore_mask_idx: []
    max_batch_size: 99999999
    save_dir: saved/fallentree_mask3d
    gpus: 1
  data:
    train_mode: train
    validation_mode: validation
    test_mode: test
    ignore_label: 255
    add_raw_coordinates: true
    add_colors: true
    add_normals: true
    in_channels: 6
    num_labels: 2
    add_instance: true
    task: instance_segmentation
    pin_memory: true
    num_workers: 8
    batch_size: 5
    test_batch_size: 1
    cache_data: false
    voxel_size: 0.15
    reps_per_epoch: 1
    cropping: false
    cropping_args:
      min_points: 30
      aspect: 0.8
      min_crop: 0.5
      max_crop: 1.0
    crop_min_size: 20
    crop_length: 2000.0
    cropping_v1: false
    train_dataloader:
      _target_: torch.utils.data.DataLoader
      shuffle: true
      pin_memory: true
      num_workers: 8
      batch_size: 5
    validation_dataloader:
      _target_: torch.utils.data.DataLoader
      shuffle: false
      pin_memory: true
      num_workers: 8
      batch_size: 1
    test_dataloader:
      _target_: torch.utils.data.DataLoader
      shuffle: false
      pin_memory: true
      num_workers: 8
      batch_size: 1
    train_dataset:
      _target_: datasets.semseg.SemanticSegmentationDataset
      dataset_name: stpls3d_fallentree
      data_dir: data/processed/stpls3d_fallentree
      image_augmentations_path: conf/augmentation/albumentations_aug.yaml
      volume_augmentations_path: conf/augmentation/volumentations_aug.yaml
      label_db_filepath: data/processed/stpls3d_fallentree/label_database.yaml
      color_mean_std: data/processed/stpls3d_fallentree/color_mean_std.yaml
      data_percent: 1.0
      mode: train
      ignore_label: 255
      num_labels: 2
      add_raw_coordinates: true
      add_colors: true
      add_normals: true
      add_instance: true
      cache_data: false
      instance_oversampling: 0.0
      place_around_existing: false
      point_per_cut: 0
      max_cut_region: 0
      flip_in_center: false
      noise_rate: 0
      resample_points: 0
      cropping: false
      cropping_args:
        min_points: 30
        aspect: 0.8
        min_crop: 0.5
        max_crop: 1.0
      is_tta: false
      crop_min_size: 20
      crop_length: 2000.0
      cropping_v1: false
      area: 5
      reps_per_epoch: 1
      eval_inner_core: -1
      filter_out_classes:
      - 0
      label_offset: 1
      is_elastic_distortion: true
      color_drop: 0.0
    validation_dataset:
      _target_: datasets.semseg.SemanticSegmentationDataset
      dataset_name: stpls3d_fallentree
      data_dir: data/processed/stpls3d_fallentree
      image_augmentations_path: null
      volume_augmentations_path: null
      label_db_filepath: data/processed/stpls3d_fallentree/label_database.yaml
      color_mean_std: data/processed/stpls3d_fallentree/color_mean_std.yaml
      data_percent: 1.0
      mode: validation
      ignore_label: 255
      num_labels: 2
      add_raw_coordinates: true
      add_colors: true
      add_normals: true
      add_instance: true
      cache_data: false
      cropping: false
      is_tta: false
      crop_min_size: 20
      crop_length: 2000.0
      cropping_v1: false
      area: 5
      on_crops: false
      eval_inner_core: -1
      filter_out_classes:
      - 0
      label_offset: 1
    test_dataset:
      _target_: datasets.semseg.SemanticSegmentationDataset
      dataset_name: stpls3d_fallentree
      data_dir: data/processed/stpls3d_fallentree
      image_augmentations_path: null
      volume_augmentations_path: null
      label_db_filepath: data/processed/stpls3d_fallentree/label_database.yaml
      color_mean_std: data/processed/stpls3d_fallentree/color_mean_std.yaml
      data_percent: 1.0
      mode: test
      ignore_label: 255
      num_labels: 2
      add_raw_coordinates: true
      add_colors: true
      add_normals: true
      add_instance: true
      cache_data: false
      cropping: false
      is_tta: false
      crop_min_size: 20
      crop_length: 2000.0
      cropping_v1: false
      area: 5
      on_crops: false
      eval_inner_core: -1
      filter_out_classes:
      - 0
      label_offset: 1
    train_collation:
      _target_: datasets.utils.VoxelizeCollate
      ignore_label: 255
      voxel_size: 0.15
      mode: train
      small_crops: false
      very_small_crops: false
      batch_instance: false
      probing: false
      task: instance_segmentation
      ignore_class_threshold: 100
      filter_out_classes:
      - 0
      label_offset: 1
      num_queries: 100
    validation_collation:
      _target_: datasets.utils.VoxelizeCollate
      ignore_label: 255
      voxel_size: 0.15
      mode: validation
      batch_instance: false
      probing: false
      task: instance_segmentation
      ignore_class_threshold: 100
      filter_out_classes:
      - 0
      label_offset: 1
      num_queries: 100
    test_collation:
      _target_: datasets.utils.VoxelizeCollate
      ignore_label: 255
      voxel_size: 0.15
      mode: test
      batch_instance: false
      probing: false
      task: instance_segmentation
      ignore_class_threshold: 100
      filter_out_classes:
      - 0
      label_offset: 1
      num_queries: 100
  logging:
  - _target_: pytorch_lightning.loggers.CSVLogger
    save_dir: saved/fallentree_mask3d
    name: lightning_logs
  model:
    _target_: models.Mask3D
    hidden_dim: 128
    dim_feedforward: 1024
    num_queries: 100
    num_heads: 8
    num_decoders: 3
    dropout: 0.0
    pre_norm: false
    use_level_embed: false
    normalize_pos_enc: true
    positional_encoding_type: fourier
    gauss_scale: 1.0
    hlevels:
    - 0
    - 1
    - 2
    - 3
    non_parametric_queries: true
    random_query_both: false
    random_normal: false
    random_queries: false
    use_np_features: false
    sample_sizes:
    - 200
    - 800
    - 3200
    - 12800
    - 51200
    max_sample_size: false
    shared_decoder: true
    num_classes: 2
    train_on_segments: false
    scatter_type: mean
    voxel_size: 0.15
    config:
      backbone:
        _target_: models.Res16UNet34C
        config:
          dialations:
          - 1
          - 1
          - 1
          - 1
          conv1_kernel_size: 5
          bn_momentum: 0.02
        in_channels: 6
        out_channels: 2
        out_fpn: true
  metrics:
    _target_: models.metrics.ConfusionMatrix
    num_classes: 2
    ignore_label: 255
  optimizer:
    _target_: torch.optim.AdamW
    lr: 0.0001
  scheduler:
    scheduler:
      _target_: torch.optim.lr_scheduler.OneCycleLR
      max_lr: 0.0001
      epochs: 1000
      steps_per_epoch: -1
    pytorch_lightning_params:
      interval: step
  trainer:
    deterministic: false
    max_epochs: 1000
    min_epochs: 1
    resume_from_checkpoint: null
    check_val_every_n_epoch: 1
    num_sanity_val_steps: 0
  callbacks:
  - _target_: pytorch_lightning.callbacks.LearningRateMonitor
  matcher:
    _target_: models.matcher.HungarianMatcher
    cost_class: 2.0
    cost_mask: 5.0
    cost_dice: 2.0
    num_points: -1
  loss:
    _target_: models.criterion.SetCriterion
    num_classes: 2
    eos_coef: 0.1
    losses:
    - labels
    - masks
    num_points: -1
    oversample_ratio: 3.0
    importance_sample_ratio: 0.75
    class_weights: -1
